services:
  backend:
    build: ./backend
    container_name: php-backend
    volumes:
      - ./backend:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - app_network

  frontend:
    build: ./frontend
    container_name: php-frontend
    volumes:
      - ./frontend:/var/www/html
    ports:
      - "8081:80"
    depends_on:
      - backend
    networks:
      - app_network

  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: meu_banco
      MYSQL_USER: usuario
      MYSQL_PASSWORD: senha
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  db_data:
